# Generated by Django 4.2.13 on 2024-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='generated_ontent',
            new_name='generated_content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
